---
- name: "Install Postfix via apt"
  apt:
    update_cache: yes
    state: present
    name:
     - postfix

- name: Install Postfix forwarder config
  template:
    src: templates/main.cf
    dest: /etc/postfix/main.cf

- name: Restart Postfix
  service:
    name: postfix
    state: restarted
    enabled: yes
...
