# {{ansible_managed}}
network:
  version: 2
  renderer: networkd
  ethernets:
    {{ ansible_default_ipv4.interface }}:
      dhcp4: true
      dhcp-identifier: mac
      dhcp4-overrides:
        use-routes: false
      gateway4: {{default_gateway}}
