---
kind: pipeline
type: docker
name: ansible

steps:
- name: ansible nightly run
  image: alpinelinux/ansible
  environment:
    ANSIBLE_HOST_KEY_CHECKING: "False"
    ANSIBLE_PRIVATE_KEY_FILE: "/drone/src/id_rsa"
    ANSIBLE_CONFIG: "/drone/src/ansible.cfg"
    CLOUDFLARE_TOKEN:
      from_secret: CLOUDFLARE_TOKEN
    SSH_KEY:
      from_secret: SSH_KEY
  commands:
    - echo "$SSH_KEY" > $PWD/id_rsa
    - chmod 0600 $PWD/id_rsa
    - ansible-galaxy collection install -r requirements.yaml
    - ansible-playbook -i inventory.yaml nightly.yaml
...
