---
- name: "Deploy basic webhost with Docker"
  hosts: keycloak, drone, swagger, guacamole, bitwarden, nexus, nextcloud 
  roles:
    - netplan
    - common
    - docker
    - webserver
    - internalsmtp
