---
- name: "Deploy basic webhost with Docker"
  hosts: nightlydocker
  roles:
    - common
    - webserver
    - internalsmtp

- name: "Deploy Jitsi Meet server"
  hosts: jitsi
  roles:
    - common
    - webserver
    - internalsmtp
    - customfirewall

- name: "Setup neko"
  hosts: neko
  roles:
    - neko
    - customfirewall
    - internalsmtp

- name: "Deploy smtpgateway to smtp.intra.tormakris.dev"
  hosts: smtp
  roles:
    - common
    - smtpgateway

- name: "Deploy backup server"
  hosts: backup
  roles:
    - common
    - internalsmtp
    - backupscript
    - backuphost
...