# TODO: Make backup user part of AD
---
- name: "Add backup user"
  user:
    name: backup
    comment: Backup user
    shell: /bin/bash

- name: Create .ssh directory of backup user
  file:
    path: /home/backup/.ssh
    state: directory

- name: Copy authorized_keys
  copy:
    src: authorized_keys
    dest: /home/backup/.ssh/authorized_keys
    mode: 0600
    owner: backup
    group: backup

- name: Copy ssh config
  copy:
    src: ssh_config
    dest: /home/backup/.ssh/config
    mode: 0600
    owner: backup
    group: backup
...
