---
- name: "Generate backupscript"
  template:
    src: backupscript.sh
    dest: /etc/cron.weekly/backupscript
    owner: root
    group: root
    mode: '0700'

- name: Create .ssh directory of root user
  file:
    path: /root/.ssh
    state: directory

- name: Copy ssh config
  copy:
    src: ssh_config
    dest: /root/.ssh/config
    mode: 0600
    owner: root
    group: root
...
