---
- name: "Generate backupscript"
  ansible.builtin.template:
    src: backupscript.sh
    dest: /etc/cron.weekly/backupscript
    owner: root
    group: root
    mode: '0700'

- name: Create .ssh directory of root user
  ansible.builtin.file:
    path: /root/.ssh
    state: directory

- name: Copy ssh config
  ansible.builtin.copy:
    src: ssh_config
    dest: /root/.ssh/config
    mode: 0600
    owner: root
    group: root
...
