---
- name: Apply custom ufw rules
  community.general.ufw:
    rule: allow
    direction: "in"
    port: "{{item.port}}"
    proto: "{{item.proto}}"
    interface: "{{item.interface}}"
  with_items: "{{ firewall }}"
