---
- name: "remove cloudinit config"
  ansible.builtin.file:
    path: /etc/netplan/50-cloud-init.yaml
    state: absent

- name: "remove installer config"
  ansible.builtin.file:
    path: /etc/netplan/00-installer-config.yaml
    state: absent

- name: "install static config"
  ansible.builtin.template:
    src: templates/netplan.yaml
    dest: /etc/netplan/00-static.yaml
  notify: netplanapply
...
