---
- name: "Use custom Ubuntu mirror"
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: 'http://hu.archive.ubuntu.com'
    replace: 'https://tormakris.jfrog.io/artifactory/ubuntu-mirror'
    backup: yes

- name: "Get JFrog password from local environment variable"
  ansible.builtin.set_fact:
    artifactory_password: "{{ lookup('env', 'ARTIFACTORY_APT_PASSWORD') }}"
  delegate_to: localhost

- name: "Render JFrog credentials configuration"
  ansible.builtin.template:
    src: jfrog.conf.template
    dest: /etc/apt/auth.conf.d/jfrog.conf

- name: "Remove Ubuntu bloatware"
  ansible.builtin.apt: 
    state: absent
    name: ubutu-server
    autoremove: yes

- name: "Update machine"
  ansible.builtin.apt:
    update_cache: yes
    upgrade: "yes"
    autoclean: yes
    autoremove: yes

- name: "Install my favourite applications"
  ansible.builtin.apt:
    update_cache: yes
    state: present
    name:
     - tmux
     - htop
     - dnsutils
     - needrestart
     - curl
     - wget
     - netcat-openbsd
     - tree
     - net-tools
     - nano
     - psmisc
     - python3
     - python3-venv
     - strace
     - ifstat
     - tcpdump
     - xxd
     - git
     - ncdu
     - cron
...
