---
- name: "Install Docker via apt"
  apt:
    update_cache: yes
    state: present
    name:
     - firewalld

- name: Start and enable firewalld
  service:
    name: firewalld
    state: restarted
    enabled: yes

- name: Permit traffic in public zone for https service
  ansible.posix.firewalld:
    zone: public
    service: https
    permanent: yes
    state: enabled

- name: Permit traffic in public zone for ssh service
  ansible.posix.firewalld:
    zone: public
    service: ssh
    permanent: yes
    state: enabled
