---
- name: "Install node exporter"
  apt:
    update_cache: yes
    state: present
    name:
     - prometheus-node-exporter

- name: Allow node-exporter via ufw
  community.general.ufw:
    rule: allow
    port: 9100
    proto: tcp
    src: 192.168.69.0/24
...
