---
- name: "Install node exporter"
  ansible.builtin.apt:
    update_cache: yes
    state: present
    name:
     - prometheus-node-exporter

- name: Allow node-exporter via ufw
  community.general.ufw:
    rule: allow
    port: 9100
    proto: tcp
    src: 192.168.69.0/24

- name: Enable and restart exporter daemon
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: restarted
    enabled: yes
...
