---
- name: "Install ufw via apt"
  apt:
    update_cache: yes
    state: present
    name:
     - ufw

- name: Reset ufw rules to default
  community.general.ufw:
    state: reset

- name: Enable ufw
  community.general.ufw:
    state: enabled

- name: Allow ssh via ufw
  community.general.ufw:
    rule: allow
    port: ssh
