---
- name: Create .ssh directory of root user
  ansible.builtin.file:
    path: /home/ansible@intra.tormakris.dev/.ssh
    state: directory
    owner: ansible@intra.tormakris.dev
    group: ansible@intra.tormakris.dev

- name: Copy authorized_keys
  ansible.builtin.copy:
    src: authorized_keys
    dest: /home/ansible@intra.tormakris.dev/.ssh/authorized_keys
    mode: 0600
    owner: ansible@intra.tormakris.dev
    group: ansible@intra.tormakris.dev

- name: "Update authorized_keys of tormakris"
  ansible.posix.authorized_key:
    user: tormakris@intra.tormakris.dev
    state: present
    key: https://static.tormakristof.eu/ssh.keys
...
