---
- name: "Install Docker via apt"
  ansible.builtin.apt:
    update_cache: yes
    state: present
    name:
     - docker.io
     - docker-compose

- name: Disable userland proxy
  ansible.builtin.copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: 644
    owner: root
    group: backup

- name: Enable and restart Docker daemon
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: yes

- name: "Add service user to docker group"
  ansible.builtin.user:
    name: service-user@intra.tormakris.dev
    groups: docker
    append: yes

- name: Allow docker exporter via ufw
  community.general.ufw:
    rule: allow
    port: "4194"
    proto: tcp
    src: 192.168.69.0/24
...
