---
ansible_host: git.intra.tormakris.dev
servicename: git
backup:
  folder: "/home/service-user"
  tarfolder: "gitea docker-compose.yml"
  host: backup.intra.tormakris.dev
  internal: true
  prearecommand: ""
  basedir: /mnt/backupstore
firewall:
  - port: "2222"
    proto: tcp
    interface: "eth0"
...
