---
firewall:
  - port: "ssh"
    proto: tcp
    interface: "eth0"
  - port: "http"
    proto: tcp
    interface: "eth1"
  - port: "https"
    proto: tcp
    interface: "eth1"
  - port: "ssh"
    proto: tcp
    interface: "eth1"
  - port: "59000:59049"
    proto: udp
    interface: "eth1"
netplan:
  default_gateway: ""
  additionalinterfaces:
    - name: "eth1"
      dhcp4: true
      dhcp6: true
      denydns: true
