---
ansible_host: zelenka.intra.tormakris.dev
firewall:
  - port: "ssh"
    proto: tcp
    interface: "eth0"
  - port: "http"
    proto: tcp
    interface: "eth0"
  - port: "https"
    proto: tcp
    interface: "eth0"
  - port: "59000:59009"
    proto: udp
    interface: "eth0"
  - port: "3478"
    proto: tcp
    interface: "eth0"
  - port: "3478"
    proto: any
    interface: "eth0"
  - port: "5349"
    proto: any
    interface: "eth0"
  - port: "9101"
    proto: tcp
    interface: "eth0"
...
