---
ansible_host: openvpn.intra.tormakris.dev
firewall:
  - port: "1194"
    proto: udp
    interface: "eth0"
  - port: "1194"
    proto: udp
    interface: "eth1"
netplan:
  default_gateway: ""
  additionalinterfaces:
    - name: "eth1"
      dhcp4: false
      dhcp6: false
      addresses:
      - "2001:738:2001:207f:0:211:211:23/64"
      gateway6: "fe80::"
      denydns: true
    - name: "eth2"
      dhcp4: true
      dhcp6: false
      denydns: true
...
