---
ansible_host: plex.intra.tormakris.dev
webserver:
  - domain: "plex.tormakristof.eu"
    port: 8080
    bigrequests: true
    https: false
netplan:
  default_gateway: "192.168.69.254"
  additionalinterfaces:
    - name: "eth1"
      dhcp4: false
      dhcp6: false
      denydns: true
      addresses:
        - '2001:738:2001:207f:0:211:211:31/64'
      gateway6: 'fe80::'
...
