---
ansible_host: postgres.intra.tormakris.dev
servicename: postgres
firewall:
  - port: "5432"
    proto: tcp
    interface: "eth0"
  - port: "9187"
    proto: tcp
    interface: "eth0"
backup:
  folder: "/var/lib/postgresql/backup"
  tarfolder: "backup"
  host: backup.intra.tormakris.dev
  internal: true
  prearecommand: "time ( sudo -u postgres pg_dumpall > /var/lib/postgresql/backup/postgres.sql )"
  basedir: /mnt/backupstore
...
