---
- name: "Install Nginx via apt"
  apt:
    update_cache: yes
    state: present
    name:
     - nginx

- name: Enable and restart nginx daemon
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: "Generate nginx configuration"
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'

- name: Reload nginx daemon
  service:
    name: nginx
    state: reloaded

- name: Allow https port via ufw
  community.general.ufw:
    rule: allow
    port: https
