---
- name: "Install Postfix via apt"
  apt:
    update_cache: yes
    state: present
    name:
     - postfix

- name: Install Postfix mail gateway config
  template:
    src: templates/main.cf
    dest: /etc/postfix/main.cf

- name: Build /etc/mailname
  shell: hostname --fqdn > /etc/mailname

- name: Restart Postfix
  service:
    name: postfix
    state: restarted
    enabled: yes

- name: Allow smtp port via ufw
  community.general.ufw:
    rule: allow
    port: smtp
    src: 192.168.69.0/24

- name: "Install postfix exporter"
  apt:
    update_cache: yes
    state: present
    name:
     - prometheus-postfix-exporter

- name: Copy exporter config
  ansible.builtin.copy:
    src: prometheus-postfix-exporter
    dest: /etc/default/prometheus-postfix-exporter
    owner: root
    group: root
    mode: '0644'

- name: Add the prometheus user to postdrop group
  ansible.builtin.user:
    name: prometheus
    groups: postdrop
    append: yes

- name: Enable and restart exporter daemon
  service:
    name: prometheus-postfix-exporter
    state: restarted
    enabled: yes

- name: Allow postfix exporter via ufw
  community.general.ufw:
    rule: allow
    port: "9154"
    proto: tcp
    src: 192.168.69.0/24
...
