---
- name: "Install Postfix via apt"
  apt:
    update_cache: yes
    state: present
    name:
     - postfix

- name: Install Postfix SASL credentials
  template:
    src: templates/sasl_passwd
    mode: 600
    dest: /etc/postfix/sasl_passwd

- name: Install Postfix mail gateway config
  template:
    src: templates/main.cf
    dest: /etc/postfix/main.cf

- name: Build hashtable of SASL creds
  command: postmap /etc/postfix/sasl_passwd

- name: Restart Postfix
  service:
    name: postfix
    state: restarted
    enabled: yes

- name: Allow smtp port via ufw
  community.general.ufw:
    rule: allow
    port: smtp